### PR TITLE
Show backups that will be migrated from PGBackups

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**
This cleans things up a bit and adds support for displaying backups from the old PGBackups system after we migrate them.

/cc @neovintage (N.B.: the backup naming scheme here is one suggested by pvh: just prefix anything coming from PGBackups with `o`--I can easily change this to something else that follows the same general mechanism)

### CODE REVIEW

**Comment by neovintage** [comment]
+1

**Comment by hgmnz** [comment]
Oh yes, +1!

**Comment by uhoh-itsmaciek** [comment]
Thanks!

**Comment by hgmnz** [comment]
woot, thanks @dickeyxxx

**Comment by neovintage** [comment]
thanks @dickeyxxx !

**Pull request merged**
