### PR TITLE
Enabled recursive Git submodule initialization for `heroku git:clone`

### PR DESCRIPTION
**Pull request by wilkinson**
This is a pretty simple edit that allows convenient use of Git submodules from within the Heroku client. All it does is add the "--recursive" flag to the system call to Git; this will automatically initialize and update [potentially nested] submodules. This can be very useful for collaborating on large, complex projects! ([documentation](http://git-scm.com/docs/git-submodule))

### CODE REVIEW

**Comment by Enelar** [comment]
@wilkinson could you please continue your attemts?
I suffer without this feature

**Comment by dickeyxxx** [comment]
Just add --recursive. It will pass through

**Comment by Enelar** [comment]
@dickeyxxx where? I use GitHub integration, and there no way to add arguments

**Comment by dickeyxxx** [comment]
This PR has nothing to do with github integration

**Pull request closed without merging**
