### PR TITLE
remove foreman and fix el capitan

### PR DESCRIPTION
**Pull request by dickeyxxx**
this fixes the toolbelt under el capitan. Many docs changes will need to be made to move everything to `heroku local` before this could be merged.

In the meantime, el capitan users can use homebrew to use the toolbelt.

### CODE REVIEW

**Comment by jordansinger** [comment]
How do we install this fix?

**Comment by dickeyxxx** [comment]
you can't, use `brew install heroku` for now

**Comment by nemonweb** [comment]
thanks

**Comment by ginolon** [comment]
Some news?

**Comment by ckirksey3** [comment]
Yeah, I also ran into this issue.

**Comment by ginolon** [comment]
But excuse me, Foreman in El Capitan is no longer needed?

**Comment by dickeyxxx** [comment]
no, it has been replaced with `heroku local`

**Pull request merged**
