### PR TITLE
Display price of add-on plan on provision/de-provision/plan-change

### PR DESCRIPTION
**Pull request by mattreduce**
To match the way we've documented the price to appear in our `heroku addons` CLI output: https://devcenter.heroku.com/articles/managing-add-ons

### CODE REVIEW

**Comment by mattreduce** [comment]
Thanks! :)

**Comment by mattreduce** [comment]
@dickeyxxx could you cut a Toolbelt release, as well? Many thanks :D

**Comment by dickeyxxx** [comment]
done

**Comment by mattreduce** [comment]
@dickeyxxx :tada: thanks!

**Pull request merged**
