### PR TITLE
use v4 for auth:whoami

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by mikehale** [comment]
I think this is doing the wrong thing. We should not run `whoami` we should lookup the logged in user based on what is in `~/.netrc`.

**Comment by dickeyxxx** [comment]
why?

**Comment by mikehale** [comment]
That's what it used to do no?

**Comment by dickeyxxx** [comment]
it did, but that seems wrong to me. The login field in netrc could be anything, it wouldn't necessarily match to the `HEROKU_API_KEY` and it might have an expired token. This ticket mentions some of the issues with the old functionality: https://github.com/heroku/heroku/issues/1149

**Comment by mikehale** [comment]
If I wanted to see my local machine user I'd just do `echo $USER` or `whoami`. If I want to see who I am on heroku I run `heroku auth:whoami`.

... just tried this locally and I'm definitely getting back my heroku user. I guess I was thinking that these were equivalent, but it seems to be doing something else which I don't understand:

```
Heroku::JSPlugin.run('whoami', nil, ARGV[1..-1])
```

and 

```
whoami
```

**Comment by dickeyxxx** [comment]
oh so when I do `Heroku::JSPlugin.run('whoami', nil, ARGV[1..-1])` what that does is call `heroku whoami` on the v4 cli at `~/.heroku/heroku-cli`. Note that I changed this after the PR to be `~/.heroku/heroku-cli auth:whoami`

**Comment by dickeyxxx** [comment]
but yeah, the new functionality calls `/account` on the api and returns the email there. This way should be better for scripting though because it's not just reading the .netrc file, it's actually checking to see if you will be able to access the API

**Comment by dickeyxxx** [comment]
some users were surprised that even though `heroku auth:whoami` returned an email that didn't mean they could actually use the API

**Comment by mikehale** [comment]
Ah, that makes sense.

**Pull request merged**
