### PR TITLE
say who is using psql and how

### PR DESCRIPTION
**Pull request by will**
Should help some issues where there are long running queries like @heroku/api sees, at least to see who is causing the issue and how.

cc @heroku/department-of-data for visibility

### CODE REVIEW

**Comment by brandur** [comment]
Went into this pull kind of expecting to see a an IP address column added to `pg:ps` or something. This is 10 million times better than that! +11111111. Thanks @will!

**Comment by pvh** [comment]
will you are the master of polishing a product

**Comment by geemus** [comment]
Awesome.

**Comment by will** [comment]
This is live in 3.28.6

```
~ ➤ h pg:psql -a will maroon
---> Connecting to HEROKU_POSTGRESQL_MAROON_URL
psql (9.4.1, server 9.1.11)
SSL connection (protocol: TLSv1, cipher: DHE-RSA-AES256-SHA, bits: 256, compression: on)
Type "help" for help.

deik3qfhu265n6=> select application_name from pg_stat_activity;
   application_name
-----------------------
 psql will interactive

(2 rows)

Time: 169.316 ms
deik3qfhu265n6=> \q
```

**Comment by dpiddy** [comment]
Very cool.

**Pull request merged**
