### PR TITLE
preauth for pgbackups schedule command

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Nice. I think this might be true for some of the other backup commands as well--I can review that soon but I don't have time right now.

**Comment by dickeyxxx** [comment]
this isn't a huge deal, the workaround is simply to preauth before the command, but if you can figure out what those might be sometime next week we could tack them on this PR

**Comment by uhoh-itsmaciek** [comment]
Yeah, can do. Feel free to remind me.

**Comment by uhoh-itsmaciek** [comment]
I think we can close this as obsolete, yeah?

**Pull request closed without merging**
