### PR TITLE
Lean on API for add-on resolution

### PR DESCRIPTION
**Pull request by bjeanes**
Yay heroku/api#4725!

I'm expecting a few test failures here that I'll need to fix. Furthermore, this should have a fair amount of manual QA done (cc @heroku/add-ons!) before this is merged.

### CODE REVIEW

**Comment by mathias** [comment]
This works well enough for me locally. But I don't really have very creative use cases in attempting to break it.

Maybe we can write tests (or at least manually reproduce and validate)  some of the more complex cases we heard from Postgres team for things like fork, follow, etc where the resolution was an issue?

**Comment by bjeanes** [comment]
@mathias all those kinds of tests [exist in API](https://github.com/heroku/api/blob/591ba59c50bce7f2ff465241b7acfed5a4fd371a/spec/mediators/addons/resolver_spec.rb) already. Since this is just an API call and not much else, I avoided adding a lot of tests that were just hitting Excon stubs which may or may not actually reflect API behaviour. This feels like something that is better tested in an integration fashion, which we don't have an answer for in the toolbelt, so thus QA. Do you have an idea of a kind of test we could add that differs from my assumptions? Would definitely be interested in exploring, if so...

**Comment by mathias** [comment]
Not really, but I didn't understand the transfer of responsibility up to the API, I guess. In that case, tests need only validate that for various types of arguments which might be treated differently (And really, I'm guessing they're not since the CLI doesn't care whether a string looks like "DATABASE" or "violet" or "papertrail") and that they all respond with the same stub, then we're good on testing it. There's no point in trying to assert anything here when the client is becoming thinner in a "thin client" sense.

**Comment by mattreduce** [comment]
@bjeanes @mathias I think [Direwolf](https://github.com/heroku/direwolf) is a good place to test various scenarios for the CLI. Thoughts?

**Comment by mathias** [comment]
That's a good point. That is the kind of integration thing we'd want to see work from both sides interacting, so it's in Direwolf's wheelhouse. 

I don't want to step on toes, but if I can help in writing Direwolf tests, let me know.

**Comment by bjeanes** [comment]
Direwolf to test the integration makes a lot of sense. As I said in stand up, I'm mostly concerned about the invocation styles I might not know about, but Direwolf tests for those that we do seems valuable.

**Comment by bjeanes** [comment]
@dickeyxxx I think this is probably good for merge.

**Comment by dickeyxxx** [comment]
not till next week

**Comment by bjeanes** [comment]
@dickeyxxx of course

**Pull request merged**
